development:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: ember-app_development
  pool: 5
  username: 
  password: 

test:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: ember-app_test
  pool: 5
  username: 
  password: 

production:
  adapter: postgresql
  encoding: utf8
  database: ember-app_production
  pool: 5
  username:
  password: